'use client';

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from '@/components/ui/dialog';

interface DisclaimerModalProps {
  trigger?: React.ReactNode;
  children?: React.ReactNode;
}

export function DisclaimerModal({ trigger, children }: DisclaimerModalProps) {
  const [open, setOpen] = useState(false);

  const defaultTrigger = (
    <a href="#disclaimer" className="underline">
      Terms of Use
    </a>
  );

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || children || defaultTrigger}
      </DialogTrigger>
      <DialogContent className="max-w-4xl h-[90vh] w-[95vw] sm:w-[90vw] p-0 flex flex-col">
        <DialogHeader className="flex-shrink-0 p-6 pb-4">
          <DialogTitle>Disclaimer and Terms of Use</DialogTitle>
        </DialogHeader>
        <div className="flex-1 overflow-y-auto px-6 pb-6">
          <div className="space-y-6 text-sm">
            <section>
              <h3 className="font-semibold text-base mb-2">
                Educational and Demonstrational Purpose
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                This platform is created solely for educational,
                demonstrational, and testing purposes. The use of names,
                likenesses, and any associated content of public figures,
                authors, thinkers, and intellectuals is intended to showcase AI
                conversation capabilities and provide an educational experience
                for users interested in exploring ideas and concepts.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                No Commercial Intent
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                We do not seek any financial gain, commercial benefit, or
                monetary profit from the use of any individual's name, likeness,
                or associated intellectual property. This platform operates as a
                non-commercial educational tool and technology demonstration.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                No Affiliation or Endorsement
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                This platform is not affiliated with, endorsed by, sponsored by,
                or connected to any of the individuals whose names or likenesses
                appear on this site. The appearance of any person's name or
                image does not imply their participation, approval, or
                endorsement of this platform or its content.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                AI-Generated Content
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                All conversations and responses are generated by artificial
                intelligence and do not represent the actual views, opinions,
                thoughts, or statements of the real individuals. The AI
                responses are based on publicly available information and should
                not be considered as authentic communications from the actual
                persons.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                Accuracy and Representation
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                The information presented may not be accurate, current, or
                complete. We make no representations or warranties about the
                accuracy of the AI-generated content or its alignment with the
                actual beliefs, philosophies, or positions of the real
                individuals. Users should not rely on this content for factual
                information about the real persons.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                Fair Use and Educational Exception
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                The use of names and publicly available information falls under
                fair use provisions for educational, commentary, and
                transformative purposes. This platform transforms publicly
                available information into an interactive educational experience
                without reproducing or distributing original copyrighted works.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                Intellectual Property Rights
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                We respect the intellectual property rights of all individuals.
                Any copyrighted material, trademarks, or proprietary content
                remains the property of their respective owners. If you believe
                your rights have been infringed, please contact us immediately.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                Contact and Removal Requests
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                If you are an individual whose name or likeness appears on this
                platform and you object to its use, or if you represent such an
                individual, please contact us. We are committed to addressing
                any concerns promptly and will remove content upon reasonable
                request.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-2">
                Contact us at:{' '}
                <span className="font-mono">contact@askauthor.com</span>
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                Technology Demonstration
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                This platform serves as a demonstration of natural language
                processing and AI conversation technologies. It is designed to
                showcase how AI can engage in educational discussions about
                various topics and ideas associated with public intellectual
                figures.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                User Responsibility
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                Users are responsible for understanding that this is an AI
                simulation and should not treat the responses as genuine
                communications from the real individuals. Users should seek
                original sources and authentic materials for accurate
                information about any person or their work.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-base mb-2">
                Updates to This Disclaimer
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                This disclaimer may be updated from time to time to reflect
                changes in our practices or legal requirements. Users are
                encouraged to review this disclaimer periodically.
              </p>
            </section>

            <div className="pt-4 border-t">
              <p className="text-xs text-muted-foreground">
                Last updated:{' '}
                {new Date().toLocaleDateString('en-US', {
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric'
                })}
              </p>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
