export default function PrivacyPage() {
  return (
    <div className="container mx-auto max-w-2xl p-6">
      <h1 className="mb-8 text-4xl font-bold">Terms and Conditions</h1>

      <div className="space-y-8">
        <section>
          <h2 className="mb-4 text-2xl font-semibold">User Agreement</h2>
          <p className="text-muted-foreground">
            By accessing and using our platform, you agree to comply with and be
            bound by the following terms and conditions. These terms govern your
            use of our AI chatbot services and the content provided.
          </p>
        </section>

        <section>
          <h2 className="mb-4 text-2xl font-semibold">Content Usage</h2>
          <p className="text-muted-foreground">
            The content generated by our AI chatbot is for personal and
            non-commercial use only. You may not reproduce, distribute, or
            create derivative works from the content without explicit
            permission.
          </p>
        </section>

        <section>
          <h2 className="mb-4 text-2xl font-semibold">
            Limitations and Liabilities
          </h2>
          <p className="text-muted-foreground">
            Our AI chatbot is designed to provide informative and engaging
            interactions. However, we do not guarantee the accuracy or
            completeness of the content. We are not liable for any errors or
            omissions in the content or for any actions taken based on the
            content.
          </p>
        </section>

        <section>
          <h2 className="mb-4 text-2xl font-semibold">User Responsibilities</h2>
          <p className="text-muted-foreground">
            Users are responsible for ensuring that their use of the platform
            complies with all applicable laws and regulations. You agree not to
            use the platform for any unlawful or prohibited activities.
          </p>
        </section>

        <section>
          <h2 className="mb-4 text-2xl font-semibold">Changes to Terms</h2>
          <p className="text-muted-foreground">
            We reserve the right to modify these terms at any time. Any changes
            will be effective immediately upon posting on our website. Your
            continued use of the platform constitutes acceptance of the revised
            terms.
          </p>
        </section>
      </div>
    </div>
  );
}
